n=input("Name of item: ")
q=input("Quantity of item: ")
p=input("Enter Price of item: ")
t=int(p)*int(q)
print("************* BILL ****************")
print("Item quantity       Price Amount ")
print(" ",n," *",q,"        ",p)
print("***********************************")
print("Total AMount to be paid: ",t)
print("***********************************")